head_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: head
    joint_speed: 1.17
    motor:
        id: 11
        init: 512 # change this
        min: 1698
        max: 330