left_shoulder_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_shoulder
    joint_speed: 1.17
    motor:
        id: 22
        init: 512 # change this
        min: 2613
        max: 0