neck_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: neck
    joint_speed: 1.17
    motor:
        id: 12
        init: 512 # change this
        min: 2846
        max: 818