right_shoulder_tip_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_shoulder
    joint_speed: 1.17
    motor:
        id: 32
        init: 512 # change this
        min: 1594
        max: 0 # double check this range